---

- name: MongoDB | Fetch 10Gen signing key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

- name: MongoDB | Add 10Gen repository
  shell: 
    echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

- name: MongoDB | Install latest MongoDB release 
  apt: pkg=mongodb-org state=present update_cache={{ update_apt_cache }} force=yes state=installed

- name: MongoDB | Push default configuration template
  template:
    src=../templates/mongodb.conf.j2
    dest=/etc/mongodb.conf
    owner=root group=root mode=0644

- name: restart mongod
  service: name=mongod state=restarted