---

user: vagrant
base_path: /home/vagrant
proj_path : /home/vagrant/dsmachine
r_mirror: http://ftp5.gwdg.de/pub/misc/cran
anaconda_url: https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda2-2.4.1-Linux-x86_64.sh
anaconda_sh: Anaconda2-2.4.1-Linux-x86_64.sh
mysql_db: "dev"
mysql_user: "dev"
mysql_root_password: "dev"
mysql_password: "dev"
clojure_url: http://repo1.maven.org/maven2/org/clojure/clojure/1.7.0/clojure-1.7.0.zip
clojure_version: clojure-1.7.0
clojure_download: clojure-1.7.0.zip
leiningen_url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein