---

user: nnfuzzy
base_path: /home/vagrant
proj_path : /home/vagrant/dsmachine
r_mirror: http://ftp5.gwdg.de/pub/misc/cran
anaconda_url: https://repo.continuum.io/archive/Anaconda3-4.1.1-Linux-x86_64.sh
anaconda_sh: Anaconda3-4.1.1-Linux-x86_64.sh
mysql_db: "dev"
mysql_user: "dev"
mysql_root_password: "dev"
mysql_password: "dev"
postgres_user: "dev"
postgres_db: "dev"
postgres_passwd: "dev"
clojure_url: http://repo1.maven.org/maven2/org/clojure/clojure/1.8.0/clojure-1.8.0.zip
clojure_version: clojure-1.8.0
clojure_download: clojure-1.8.0.zip
leiningen_url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
julia_url: https://julialang.s3.amazonaws.com/bin/linux/x64/0.4/julia-0.4.5-linux-x86_64.tar.gz
julia_download: julia-0.4.5-linux-x86_64.tar.gz
julia_folder: julia
spark_bin_url: http://d3kbcqa49mib13.cloudfront.net/spark-2.0.0-bin-hadoop2.7.tgz
spark_bin_download: spark-2.0.0-bin-hadoop2.7.tgz
spark_bin_version:  spark-2.0.0-bin-hadoop2.7