---

  - name: Download spark
    get_url: >
      url={{ spark_bin_url }}
      dest=/tmp/{{ spark_bin_download }}
      owner={{ user }}
      group={{ user }}
      mode=0755

  - name: unpack spark archive
    unarchive: src=/tmp/{{ spark_bin_download }}  dest=/home/{{ user }} copy=no

  - name: create spark home variable
    lineinfile: >
      dest=/home/{{ user }}/.bashrc
      line='spark_HOME=/home/{{ user }}/{{ spark_bin_version }}'
      state=present

  - name: create spark path variable
    lineinfile: >
      dest=/home/{{ user }}/.bashrc
      line='export PATH=$spark_HOME/bin:$PATH'
      state=present